### ISSUE TITLE
win10上,直接在picgo目录下用命令行安装也失败

### ISSUE THREAD

**Issue by hss01248** [zhanghuid/picgo-plugin-gitee#6]
94 verbose stack Error: optipng-bin@6.0.0 postinstall: `node lib/install.js`
194 verbose stack Exit status 1
194 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
194 verbose stack     at EventEmitter.emit (events.js:315:20)
194 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
194 verbose stack     at ChildProcess.emit (events.js:315:20)
194 verbose stack     at maybeClose (internal/child_process.js:1021:16)
194 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
195 verbose pkgid optipng-bin@6.0.0
196 verbose cwd C:\Users\Administrator\AppData\Roaming\picgo
197 verbose Windows_NT 10.0.18363
198 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "picgo-plugin-gitee"
199 verbose node v12.18.0
200 verbose npm  v6.14.4
201 error code ELIFECYCLE
202 error errno 1
203 error optipng-bin@6.0.0 postinstall: `node lib/install.js`
203 error Exit status 1
204 error Failed at the optipng-bin@6.0.0 postinstall script.

**Comment by hss01248** [comment]
raw.github访问不了的问题,配了host就好了
